// AUTOGENERATED for fiu-dash-preview by scripts/build-preview-stub.sh.
// Do not edit here — edit the generator in fiu-dash.
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import fixtures from "./fixtures.json";

type Row = Record<string, unknown>;
const tableData = (table: string): Row[] =>
  (fixtures as Record<string, Row[]>)[table] ?? [];

const makeChain = (table: string): any => {
  const data = tableData(table);
  const chain: any = {};
  const passthrough = [
    "select", "eq", "neq", "in", "is", "gte", "lte", "gt", "lt",
    "like", "ilike", "or", "and", "not", "contains", "containedBy",
    "filter", "match", "order", "limit", "range", "textSearch",
  ];
  for (const m of passthrough) chain[m] = () => chain;
  chain.single = () => Promise.resolve({ data: data[0] ?? null, error: null });
  chain.maybeSingle = () => Promise.resolve({ data: data[0] ?? null, error: null });
  chain.insert = () => Promise.resolve({ data: null, error: null });
  chain.update = () => chain;
  chain.upsert = () => Promise.resolve({ data: null, error: null });
  chain.delete = () => chain;
  chain.then = (resolve: any, reject?: any) =>
    Promise.resolve({ data, error: null, count: data.length }).then(resolve, reject);
  return chain;
};

const fakeUser = {
  id: "00000000-0000-0000-0000-000000000000",
  email: "preview@local",
  aud: "authenticated",
  role: "authenticated",
  app_metadata: {},
  user_metadata: { name: "Preview User" },
  created_at: new Date().toISOString(),
};

const fakeSession = {
  access_token: "preview",
  refresh_token: "preview",
  token_type: "bearer",
  expires_in: 3600,
  expires_at: Math.floor(Date.now() / 1000) + 3600,
  user: fakeUser,
};

export const supabase = {
  from: (table: string) => makeChain(table),
  auth: {
    getSession: () => Promise.resolve({ data: { session: fakeSession }, error: null }),
    getUser: () => Promise.resolve({ data: { user: fakeUser }, error: null }),
    onAuthStateChange: (cb: any) => {
      queueMicrotask(() => cb("SIGNED_IN", fakeSession));
      return { data: { subscription: { unsubscribe: () => {} } } };
    },
    signInWithPassword: () =>
      Promise.resolve({ data: { session: fakeSession, user: fakeUser }, error: null }),
    signUp: () =>
      Promise.resolve({ data: { session: fakeSession, user: fakeUser }, error: null }),
    signOut: () => Promise.resolve({ error: null }),
    resetPasswordForEmail: () => Promise.resolve({ data: {}, error: null }),
    updateUser: () => Promise.resolve({ data: { user: fakeUser }, error: null }),
  },
  channel: () => ({
    on: () => ({ subscribe: () => ({ unsubscribe: () => {} }) }),
    subscribe: () => ({ unsubscribe: () => {} }),
    unsubscribe: () => {},
  }),
  removeChannel: () => {},
  removeAllChannels: () => {},
  rpc: () => Promise.resolve({ data: [], error: null }),
  functions: { invoke: () => Promise.resolve({ data: null, error: null }) },
  storage: {
    from: () => ({
      upload: () => Promise.resolve({ data: null, error: null }),
      download: () => Promise.resolve({ data: null, error: null }),
      remove: () => Promise.resolve({ data: null, error: null }),
      list: () => Promise.resolve({ data: [], error: null }),
      getPublicUrl: () => ({ data: { publicUrl: "" } }),
      createSignedUrl: () =>
        Promise.resolve({ data: { signedUrl: "" }, error: null }),
    }),
  },
} as unknown as SupabaseClient<Database>;
